sudo: false
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - ROSWS=wstool
    - BUILDER=catkin
    - USE_DEB=true
  matrix:
    - ROS_DISTRO=hydro  USE_JENKINS=true
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
matrix:
  allow_failures:
    - env: ROS_DISTRO=hydro  USE_JENKINS=true
    - env: ROS_DISTRO=jade
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
