sudo: false
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - ROS_PARALLEL_JOBS="-j8"
  matrix:
    - ROS_DISTRO=hydro  USE_JENKINS=true ROSWS=wstool BUILDER=catkin USE_DEB=true
    - ROS_DISTRO=indigo                  ROSWS=wstool BUILDER=catkin USE_DEB=true
script: source .travis/travis.sh
notifications:
  email:
    on_success: always
    on_failure: always
